### ISSUE TITLE
All fields are getting overwritten with every login ;-/

### ISSUE THREAD

**Issue by koehlersimon** [kalypso63/social_auth#10]
Hey, really great extension, I love using it and works like a charm. But I have a problem now. I created a custom account edit page (custom extension), to enable users who logged in with facebook, to add company data, address and other fields after registration/login. Now I figured out that in the function "getUser" of your class "SocialAuthenticationService", you overwrite all these fields at every login. Maybe you could integrate a more detailed TypoScript configuration to enable admins to select only specific fields from facebook that should be fetched? I support development when you can do it and send me your PayPal address! Thanks a lot

**Comment by kalypso63** [comment]
Hey,

Thank you for your feedback. I can develop this feature next week . If you are agree, i send to you my PayPal address.

**Comment by kalypso63** [comment]
And what is your version of TYPO3 ?

**Comment by koehlersimon** [comment]
Sure, lets do it ;) I am using 9.5.4 and I helped myself already with downloading your Class and added some comments to make it work for my project. But only temporary for now.

**Comment by kalypso63** [comment]
@koehlersimon A new version has been uploaded on TER (1.2.6). This version include a new param in Extension Configuration (Last tab and last field). You can exclude some fields on update after each login.

My address for PayPal : vanclooster.mickael@gmail.com or my paypal.me : https://www.paypal.me/vancloostermickael

**Comment by kalypso63** [comment]
@koehlersimon Have you tried my new release ?

**Comment by koehlersimon** [comment]
Hey sorry I'm in my bed unexpected sickness for few days. I think I would test it tomorrow. ThanksEnviado desde mi HUAWEI Mate 10 lite-------- Originalnachricht --------Betreff: Re: [kalypso63/social_auth] All fields are getting overwritten with every login ;-/ (#10)Von: VANCLOOSTER Mickael An: kalypso63/social_auth Cc: Simon Köhler ,Mention @koehlersimon Have you tried my new release ?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/kalypso63/social_auth","title":"kalypso63/social_auth","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/kalypso63/social_auth"}},"updates":{"snippets":[{"icon":"PERSON","message":"@kalypso63 in #10: @koehlersimon Have you tried my new release ?"}],"action":{"name":"View Issue","url":"https://github.com/kalypso63/social_auth/issues/10#issuecomment-461099792"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/kalypso63/social_auth/issues/10#issuecomment-461099792",
"url": "https://github.com/kalypso63/social_auth/issues/10#issuecomment-461099792",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by koehlersimon** [comment]
Hey I was sick sorry. I will test it this weekend and definitely get back to you. Thanks!

**Comment by koehlersimon** [comment]
I have installed the new version and it seems to work, thanks. Just sent you some money on PayPal, keep up the good work!

**Comment by kalypso63** [comment]
@koehlersimon 👍
